### ISSUE TITLE
Is this example outdated?

### ISSUE THREAD

**Issue by odarbelaeze** [bendemaree/falcon-graphene#1]
In the `README` file you have something like `falcon_graphene.register(api, RootQuery)`, but I don't see the register function defined anywhere, furthermore the example doesn't mention it anymore, is it just outdated or am I missing something?

**Comment by bendemaree** [comment]
Hello @odarbelaeze! Sorry for the confusion; I’ll get the example and the readme updated today. Thanks for raising the issue. 😊

**Comment by bendemaree** [comment]
Hey @odarbelaeze; sorry for the delay. I updated the main README with the toy server in `examples/clocks.py`, which uses the newer `GrapheneRouter` (which replaced the `register(api, query)` style.

Let me know if you have any other difficulties, suggestions, etc. The project is pretty new still, as you have probably gathered. 😉
